# Generated by Django 4.1.11 on 2023-09-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepId', models.AutoField(primary_key=True, serialize=False)),
                ('DepName', models.CharField(max_length=100)),
            ],
        ),
    ]
